repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.260
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - --quiet
        files: ^((homeassistant|pylint|script|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
          - --branch=rc
  - repo: local
    hooks:
      # Run mypy through our wrapper script in order to get the possible
      # pyenv and/or virtualenv activated; it may not have been e.g. if
      # committing from a GUI tool that was not launched from an activated
      # shell.
      - id: mypy
        name: mypy
        entry: mypy
        language: script
        types: [python]
        require_serial: true
        files: ^(homeassistant|pylint)/.+\.py$
      - id: pylint
        name: pylint
        entry: pylint -j 0 --ignore-missing-annotations=y
        language: script
        types: [python]
        files: ^homeassistant/.+\.py$
      - id: hassfest
        name: hassfest
        entry: python3 -m script.hassfest
        pass_filenames: false
        language: script
        types: [text]
        files: ^(homeassistant/.+/(manifest|strings)\.json|homeassistant/brands/.*\.json|\.coveragerc|homeassistant/.+/services\.yaml|script/hassfest/(?!metadata|mypy_config).+\.py)$
      - id: hassfest-metadata
        name: hassfest-metadata
        entry: python3 -m script.hassfest -p metadata
        pass_filenames: false
        language: script
        types: [text]
        files: ^(script/hassfest/metadata\.py|homeassistant/const\.py$|pyproject\.toml)$
      - id: hassfest-mypy-config
        name: hassfest-mypy-config
        entry: python3 -m script.hassfest -p mypy_config
        pass_filenames: false
        language: script
        types: [text]
        files: ^(script/hassfest/mypy_config\.py|\.strict-typing|mypy\.ini)$
